config/routes.rb
Rails.application.routes.draw do

  root 'application#welcome'

  devise_for :accounts#, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :games do
    member do
      get 'engage'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :games, :through => :players
end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :owner, :class_name => 'Account'

  has_many :players
  has_many :accounts, :through => :players, :source => :account

  # state_machine :status, :initial => :pending do
  #   # before_transition :pending => any - :pending#, :do => :put_on_seatbelt
  #   after_transition :on => :preparing, :do => :assign_roles
  #
  #   event :prepare do
  #     transition :pending => :preparing
  #   end
  #
  #   event :start do
  #     transition :preparing => :started
  #   end
  #
  #   event :end do
  #     transition :started => :finished
  #   end
  # end
  #
  # state_machine :daytime, :initial => :night do
  #   # morning
  #   # noon
  #   # evening
  #   # night
  # end

  def engage account
    self.owner = account if self.players_count == 0
    self.accounts.append account
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :account
  belongs_to :game, :counter_cache => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :players
  has_many :accounts, :through => :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception

  def welcome
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :authenticate_account!

  def index
    @games = Game.all
  end

  def show
    @game = Game.find params[:id]
  end

  def new
    @game = Game.new
  end

  def engage
    @game = Game.find params[:id]
    @game.engage current_account
    @game.save

    flash[:success] = "Successfully joined game ##{@game.id}"
    redirect_to game_path @game
  end

  def create
    @game = Game.new params[:game]
    @game.engage current_account
    @game.save

    flash[:success] = 'Game successfully created!'
    redirect_to games_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class key
    case key
      when 'notice' then 'alert-info'
      when 'success' then 'alert-success'
      when 'error' then 'alert-danger'
      when 'alert' then 'alert-warning'
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/application/welcome.slim
div class='container'
  h1 Welcome
  - if current_account
    p Hello, #{current_account.email} [#{link_to "Sign out", destroy_account_session_path}]!
  - else
    p Hello, Guest! #{link_to "Sign in", new_account_session_path}

app/views/games/index.slim
div class='container'
  h1 Games
  = link_to 'New Game', new_game_path, :class => 'btn btn-default'
  table class='table table-hover'
    thead
      tr
        td #
        td created_at
        td updated_at
        td creator
        td players
        td state
        td actions
    tbody
      - @games.each do |game|
        tr
          td #{game.id}
          td #{game.created_at}
          td #{game.updated_at}
          - if game.owner.present?
            td #{game.owner.email}
          - else
            td Not defined
          td #{game.players_count} / #{game.players_count_max}
          td #{game.status_state}
          td
            = link_to 'Join', engage_game_path(game), :class => 'btn btn-xs btn-success'
            = link_to 'View', game_path(game), :class => 'btn btn-xs btn-info'

app/views/games/new.slim
div class='container'
  h1 New Game
  = link_to 'Back', request.referrer, :class => 'btn btn-default'
  = form_for @game do |form|
    = form.submit :class => 'btn btn-primary'

app/views/games/show.slim
div class='container'
  h1 Game ##{@game.id}
  = link_to 'Back', games_path, :class => 'btn btn-default'
  h3 Owner
  - if @game.owner.present?
    p #{@game.owner.email}
  - else
    p No owner found
  h3 Players
  - if @game.players.any?
    table class='table'
      thead
        tr
          td #
          td E-mail
      tbody
        - @game.accounts.each do |account|
          tr
            td #{account.id}
            td #{account.email}
  - else
    p No players found.

app/views/layouts/_partials/_flash.slim
- if flash.any?
  div class='container'
    - flash.each do |key, value|
      div role='alert' class=['alert', 'alert-dismissable', flash_class(key)]
        button type='button' class='close' data-dismiss='alert'
          span aria-hidden='true' &times;
          span class='sr-only' Close
        p = value

app/views/layouts/_partials/_navbar.slim
div class='container'
  nav.navbar.navbar-default role="navigation"
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Townsville', root_path, :class => 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Games', games_path

app/views/layouts/application.slim
doctype html
html
  head
    title Townsville
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    == render 'layouts/_partials/navbar'
    == render 'layouts/_partials/flash'
    = yield